### ISSUE TITLE
Can not create directory  .../Neo4j::Rails::Relationship_exact

### ISSUE THREAD

**Issue by tzmgit** [andreasronge/neo4j-wrapper#11]
I try to update neo4j from  1.3.1 to 2.2.3. 
Exception occur when save relation node. Code like this:
class Project::ModelA < Neo4j::Rails::Model
end
class Project::ModelB < Neo4j::Rails::Model
  has_n(:others).to(ModelA)
end

a = ModelA.new
a.save

b = ModelB.new
b.others << a
b.save # here throw exception

In message.log:
java.io.IOException: Cannot create directory: ...index\lucene\relationship\Neo4j::Rails::Relationship_exact

**Comment by elena-pechko** [comment]
I found another place with the same exception:

Caused by: java.io.IOException: Cannot create directory: ..\index\lucene\relationship\Neo4j::Rails::Relationship_exact
        at org.apache.lucene.store.NativeFSLock.obtain(NativeFSLockFactory.java:171)
        at org.apache.lucene.store.Lock.obtain(Lock.java:72)
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1108)
        at org.neo4j.index.impl.lucene.LuceneDataSource.newIndexWriter(LuceneDataSource.java:674)
        ... 377 more
org.neo4j.graphdb.TransactionFailureException: Failed to mark transaction as rollback only.
org/neo4j/kernel/TopLevelTransaction.java:85:in `failure'
.../neo4j-2.2.3-java/lib/neo4j/rails/transaction.rb:67:in`finish'
.../neo4j-2.2.3-java/lib/neo4j/rails/transaction.rb:87:in `run'
.../neo4j-2.2.3-java/lib/neo4j/rails/tx_methods.rb:9:in`save'
.../neo4j-2.2.3-java/lib/neo4j/rails/validations.rb:19:in `save'
.../neo4j-2.2.3-java/lib/neo4j/rails/persistence.rb:33:in`save!'

OS: Windows 7, 64 bit

**Comment by andreasronge** [comment]
Strange, this has worked in some old version:
The location of the bug might be somewhere here: https://github.com/andreasronge/neo4j-wrapper/blob/master/lib/neo4j-wrapper/class_methods.rb#L35
